title: Jordan Marinov
description: >-
  FPV drones, RC multirotors, guitars, and the DIY/maker & software projects behind them.
baseurl: ""
url: "https://jaisor.github.io"
github_username: jaisor

theme: jekyll-theme-leap-day

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
